### ISSUE TITLE
Port to .NET Core

### ISSUE THREAD

**Issue by ForNeVeR** [xmppo/Jabber-Net#1]
### Prerequisites
- [x] #2:  Drop Component-based stuff
- [x] #4: Remove Form support from CertificatePrompt
- [x] #5: Drop System.ComponentModel.ISynchronizeInvoke
- [x] #14: Remove binary files from the repository
- [x] #15: Build system changes
- [x] #17: Project reorganization
- [ ] #61: .NET Core-based build system
- [ ] #7: Use alternative mock library in tests
- [ ] #3: Migrate to .NET Core-compatible XML API
- [ ] #60: .NET Core-compatible zlib.net replacement
