### ISSUE TITLE
Big project cleanup

### ISSUE THREAD

**Issue by ForNeVeR** [xmppo/Jabber-Net#11]
Currently there're some issues with the project organization:
- [x] #12: Remove unused files from the repository
- [x] #25: Delete .user files
- [x] #14: Remove binary files from the repository
- [x] ~~#18: netlib.Dns license issues~~
- [x] #28: CRLF conversion
- [x] #30: stringprep.xml
- [x] #32: *.resx files
- [x] #23: Clarify the licensing
- [x] #15: Build system changes
- [x] #29: stringprep/ResTool
- [x] #34: "either JOSL or the GPL" licensed files
- [x] #35: Standartize AssemblyInfo
- [x] #13: Restore the project documentation
- [x] #16: Enable VB.Example project
- [x] #17: Project reorganization
- [x] #19: Class versioning issues
- [x] #50: Add info to licenses section
- [x] #51: xpnet license notice
- [x] #48: stringprep

After all of these tasks are done, reevaluate the project state and check if anything else should be cleaned up.

**Comment by ForNeVeR** [comment]
Everything is done!
