### ISSUE TITLE
"either JOSL or the GPL" licensed files

### ISSUE THREAD

**Issue by ForNeVeR** [xmppo/Jabber-Net#34]
There's a bunch of files with the (_terribly_) wrong license header (licensed under "either JOSL or the GPL"):
- [x] [`CertUtil.cs`](https://github.com/ForNeVeR/Jabber-Net/blob/e2de080dff74e11036662015d6aa8002dc3b314f/bedrock/net/CertUtil.cs)
- [x] [`ConsoleClient/Makefile`](https://github.com/ForNeVeR/Jabber-Net/blob/35c1c2eee2056275da511f3759f400a9c0c922ea/ConsoleClient/Makefile) (managed by #15)
- [x] [`SynchElementStream.cs`](https://github.com/ForNeVeR/Jabber-Net/blob/3dcd0a2e6dc2db8f4591125943601177a6244708/jabber/protocol/SynchElementStream.cs)
- [x] [`Makefile`](https://github.com/ForNeVeR/Jabber-Net/blob/08777c43d3ab337784473207b6e02fec848dcfd2/Makefile) (managed by #15)
- [x] [`stringprep/AssemblyInfo.cs`](https://github.com/ForNeVeR/Jabber-Net/blob/b75830e1922121f931a6afc4a574f7174fa95786/stringprep/AssemblyInfo.cs)
- [x] [`stringprep/Makefile`](https://github.com/ForNeVeR/Jabber-Net/blob/af8e539a1359268315066c1d585d9f995e8cb92e/stringprep/Makefile) (managed by #15)
- [x] [`stringprep/ResTool/AssemblyInfo.cs`](https://github.com/ForNeVeR/Jabber-Net/blob/c0585e06be9a1d2391a4356f25fcbd1566bc21c5/stringprep/ResTool/AssemblyInfo.cs) (managed by #29)
- [x] [`Main.cs`](https://github.com/ForNeVeR/Jabber-Net/blob/af8e539a1359268315066c1d585d9f995e8cb92e/stringprep/ResTool/Main.cs) (managed by #29)
- [x] [`steps/ResourceLoader.cs`](https://github.com/ForNeVeR/Jabber-Net/commits/c0585e06be9a1d2391a4356f25fcbd1566bc21c5/stringprep/steps/ResourceLoader.cs)
- [x] [`unicode/ResourceLoader.cs`](https://github.com/ForNeVeR/Jabber-Net/commits/develop/stringprep/unicode/ResourceLoader.cs)
- [x] [`test/Makefile`](https://github.com/ForNeVeR/Jabber-Net/blob/develop/test/Makefile) (managed by #15)
- [x] [`TestDecompose.cs`](https://github.com/ForNeVeR/Jabber-Net/blob/develop/test/stringprep/TestDecompose.cs)

All of these files should be removed and destroyed and killed with fire ASAP no matter what. This is the top priority task.
- [x] don't forget to update `Licensing.md`
- [x] validate that there're no additional GPL-licensed files
