### ISSUE TITLE
.NET Core-based build system

### ISSUE THREAD

**Issue by ForNeVeR** [xmppo/Jabber-Net#61]
I want the whole project (or the most of it) to be built using `dotnet` tool. Some important thoughts:
1. I want the project to be editable using Visual Studio, so probably the `sln` file still need to be used. It'll reference `csproj` and `xproj` files (or maybe `project.json` directly?).
2. There's a couple of .NET Core-incompatible projects (Windows Forms controls and samples), I'm not sure whether they need or can be converted (_**UPD**: it seems they can_).
3. At the current state project won't support .NET Core itself (see #1 for the current state) but I think that `dotnet` could actually build FullCLR projects; need to check that.

@gsomix and sleepyvenom have shown interest in the task, although I'll obviously have to take a leading role in the implementation.

I've started initial work in the [feature/61-dotnet-core branch](https://github.com/ForNeVeR/Jabber-Net/tree/feature/61-dotnet-core). This task have a couple of dependencies:
- [x] #62: Test fails on Mono 4.6
- [x] #46: Revive examples
- [x] #72: Remove Muzzle reference from the main test library
- [x] Convert every project to `dotnet` (see #74, currently impossible for VB.NET)
- [x] ~~Rebase #63~~
- [x] Check if the ConsoleClient works
- [ ] _(new from 2016-12-05)_ try preview 3 and MSBuild stuff
- [ ] Port GUI projects back to MSBuild
- [ ] Check if the GUI client works
- [ ] Check if the VB.NET example works
- [ ] Fix both CI services
- [ ] Update the documentation accordingly

**Comment by ForNeVeR** [comment]
I've decided to port all the GUI projects back to regular MSBuild for now. After that the solution may be merged.
